import Link from "next/link";
import { ArrowLeft, Download, ExternalLink } from "lucide-react";
import { notFound } from "next/navigation";
import { ApplicationStatusBadge } from "@/components/applications/application-status-badge";
import { ApplicationTimeline } from "@/components/applications/timeline";
import { addApplicationNote, refreshReadiness, updateApplicationStatus } from "@/lib/actions/applications";
import { createClient } from "@/lib/supabase/server";
import type { ApplicationStatus } from "@/lib/applications/types";

export default async function ApplicationDetailPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{error?:string}>}){
 const {id}=await params; const query=await searchParams; const db=await createClient();
 const {data:app}=await db.from("applications").select("id,status,match_score,source_apply_url,submitted_at,selected_resume_draft_id,selected_cover_letter_draft_id,jobs(id,title,location,status,source_url,companies(name)),application_events(id,event_type,event_data,created_at),application_email_events(id,classification,confidence,sender_email,subject,received_at),application_notes(id,content,created_at),application_documents(id,document_type,document_draft_id,document_version_id)").eq("id",id).maybeSingle();
 if(!app)notFound(); const job=app.jobs as unknown as {id:string;title:string;location:string|null;status:string;source_url:string;companies:{name:string}}; const status=app.status as ApplicationStatus;
 const terminal=["SUBMITTED","INTERVIEW","REJECTED","OFFER","WITHDRAWN","ARCHIVED"].includes(status);
 return <main className="mx-auto max-w-6xl space-y-6 p-5 sm:p-8"><Link href="/applications" className="inline-flex items-center gap-2 text-sm font-semibold text-zinc-500"><ArrowLeft className="size-4"/>Applications</Link><header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm text-zinc-500">{job.companies.name}</p><h1 className="mt-1 text-3xl font-semibold">{job.title}</h1><p className="mt-1 text-sm text-zinc-500">{job.location??"Location not listed"} · {app.match_score??"--"}% match</p></div><ApplicationStatusBadge status={status}/></header>
 {job.status!=="active"&&!terminal&&<div className="rounded-xl bg-amber-50 p-4 text-sm text-amber-800">This job is no longer listed by the employer.</div>}{query.error&&<div className="rounded-xl bg-rose-50 p-4 text-sm text-rose-700">{query.error==="missing-url"?"The employer application URL is missing.":"This application is not ready to open."}</div>}
 <div className="grid gap-6 lg:grid-cols-[1fr_360px]"><div className="space-y-6"><section className="card p-6"><h2 className="font-semibold">Documents</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{[["Resume",app.selected_resume_draft_id],["Cover letter",app.selected_cover_letter_draft_id]] .map(([label,draft])=><div key={label} className="rounded-xl bg-zinc-50 p-4"><p className="text-xs text-zinc-400">{label}</p><p className="mt-1 text-sm font-semibold">{draft?"Approved":"Missing, optional, or needs approval"}</p>{draft&&<a href={`/api/documents/${draft}/pdf`} className="mt-3 inline-flex items-center gap-1 text-xs font-semibold text-accent-700"><Download className="size-3"/>Download</a>}</div>)}</div><div className="mt-4 flex gap-2"><Link className="button-secondary !py-2" href={`/jobs/${job.id}/prepare`}>Prepare or review</Link><form action={refreshReadiness}><input type="hidden" name="applicationId" value={id}/><button className="button-secondary !py-2">Check readiness</button></form></div></section>
 <section className="card p-6"><h2 className="font-semibold">Notes</h2><form action={addApplicationNote} className="mt-4"><input type="hidden" name="applicationId" value={id}/><textarea name="content" required maxLength={5000} className="min-h-24 w-full rounded-xl border p-3 text-sm" placeholder="Add a private note..."/><button className="button-primary mt-2 !py-2">Add note</button></form><div className="mt-5 space-y-3">{(app.application_notes??[]).map(n=><div key={n.id} className="rounded-xl bg-zinc-50 p-3"><p className="text-sm">{n.content}</p><time className="mt-2 block text-xs text-zinc-400">{new Date(n.created_at).toLocaleString()}</time></div>)}</div></section></div>
 <aside className="space-y-6"><section className="card p-5"><h2 className="font-semibold">Next action</h2><div className="mt-4 space-y-2">{status==="READY_TO_APPLY"&&<a href={`/applications/${id}/apply`} target="_blank" rel="noopener noreferrer" className="button-primary w-full">Apply on employer site <ExternalLink className="size-4"/></a>}{status==="APPLYING"&&<><p className="text-sm">Did you submit this application?</p>{[["SUBMITTED","Yes, submitted"],["READY_TO_APPLY","Not yet"],["NEEDS_USER_ACTION","I need help"],["FAILED","Application failed"]].map(([s,label])=><form action={updateApplicationStatus} key={s}><input type="hidden" name="applicationId" value={id}/><input type="hidden" name="status" value={s}/><button className="button-secondary w-full !py-2">{label}</button></form>)}</>}{status==="SAVED"&&<form action={updateApplicationStatus}><input type="hidden" name="applicationId" value={id}/><input type="hidden" name="status" value="PREPARING"/><button className="button-primary w-full">Start preparing</button></form>}<a href={job.source_url} target="_blank" rel="noopener noreferrer" className="button-secondary w-full !py-2">Original listing</a><form action={updateApplicationStatus}><input type="hidden" name="applicationId" value={id}/><input type="hidden" name="status" value="ARCHIVED"/><input type="hidden" name="manual" value="true"/><button className="w-full py-2 text-xs font-semibold text-zinc-400">Archive</button></form></div></section><section className="card p-5"><h2 className="font-semibold">Timeline</h2><div className="mt-5"><ApplicationTimeline events={[...(app.application_events??[]),...(app.application_email_events??[]).map(event=>({id:event.id,event_type:event.classification,event_data:{sender:event.sender_email,subject:event.subject,confidence:event.confidence},created_at:event.received_at}))].sort((a,b)=>a.created_at.localeCompare(b.created_at)) as never}/></div></section></aside></div></main>;
}
