import type { EmailProviderClient, ProviderTokens } from "./types";
type GmailPayload={mimeType?:string;body?:{data?:string};parts?:GmailPayload[]};
const tokenUrl="https://oauth2.googleapis.com/token";
const credentials=()=>{const clientId=process.env.GOOGLE_EMAIL_CLIENT_ID,clientSecret=process.env.GOOGLE_EMAIL_CLIENT_SECRET;if(!clientId||!clientSecret)throw new Error("GMAIL_OAUTH_NOT_CONFIGURED");return{clientId,clientSecret}};
const tokens=(value:{access_token:string;refresh_token?:string;expires_in:number;scope?:string}):ProviderTokens=>({accessToken:value.access_token,refreshToken:value.refresh_token,expiresAt:new Date(Date.now()+value.expires_in*1000).toISOString(),scopes:value.scope?.split(" ")??["https://www.googleapis.com/auth/gmail.readonly"]});
async function tokenRequest(body:URLSearchParams){const response=await fetch(tokenUrl,{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body,signal:AbortSignal.timeout(15_000)});if(!response.ok)throw new Error(`GMAIL_TOKEN_${response.status}`);return tokens(await response.json())}
const header=(headers:{name:string;value:string}[]|undefined,name:string)=>headers?.find(item=>item.name.toLowerCase()===name)?.value??"";
const sender=(value:string)=>value.match(/<([^>]+)>/)?.[1]??value.match(/[\w.+-]+@[\w.-]+/)?.[0]??null;
const decode=(value?:string)=>value?Buffer.from(value.replace(/-/g,"+").replace(/_/g,"/"),"base64").toString("utf8"):"";
const bodyText=(payload:GmailPayload|undefined):string=>{if(payload?.mimeType==="text/plain"&&payload.body?.data)return decode(payload.body.data);for(const part of payload?.parts??[]){const found=bodyText(part);if(found)return found}return""};
export const gmailProvider:EmailProviderClient={
 async connect(code,redirectUri){const c=credentials();return tokenRequest(new URLSearchParams({code,client_id:c.clientId,client_secret:c.clientSecret,redirect_uri:redirectUri,grant_type:"authorization_code"}))},
 async refreshToken(refreshToken){const c=credentials();return tokenRequest(new URLSearchParams({refresh_token:refreshToken,client_id:c.clientId,client_secret:c.clientSecret,grant_type:"refresh_token"}))},
 async listMessages(accessToken,cursor,lastSyncAt){const parsed=cursor?.startsWith("gmail:")?JSON.parse(Buffer.from(cursor.slice(6),"base64url").toString("utf8"))as{query:string;pageToken:string}:null,query=parsed?.query??(lastSyncAt?`after:${Math.floor(new Date(lastSyncAt).getTime()/1000)}`:"newer_than:30d"),url=new URL("https://gmail.googleapis.com/gmail/v1/users/me/messages");url.searchParams.set("maxResults","100");url.searchParams.set("q",query);if(parsed?.pageToken)url.searchParams.set("pageToken",parsed.pageToken);const response=await fetch(url,{headers:{authorization:`Bearer ${accessToken}`},signal:AbortSignal.timeout(20_000)});if(!response.ok)throw new Error(`GMAIL_LIST_${response.status}`);const data=await response.json(),nextCursor=data.nextPageToken?`gmail:${Buffer.from(JSON.stringify({query,pageToken:data.nextPageToken})).toString("base64url")}`:undefined;return{messages:data.messages??[],nextCursor}},
 async getMessage(accessToken,messageId){const response=await fetch(`https://gmail.googleapis.com/gmail/v1/users/me/messages/${encodeURIComponent(messageId)}?format=full`,{headers:{authorization:`Bearer ${accessToken}`},signal:AbortSignal.timeout(20_000)});if(!response.ok)throw new Error(`GMAIL_MESSAGE_${response.status}`);const data=await response.json(),headers=data.payload?.headers;return{id:data.id,threadId:data.threadId,senderEmail:sender(header(headers,"from")),subject:header(headers,"subject"),receivedAt:new Date(Number(data.internalDate)).toISOString(),text:(bodyText(data.payload)||data.snippet||"").slice(0,20_000)}},
 async disconnect(accessToken,refreshToken){const token=refreshToken??accessToken;if(token)await fetch(`https://oauth2.googleapis.com/revoke?token=${encodeURIComponent(token)}`,{method:"POST",signal:AbortSignal.timeout(10_000)}).catch(()=>undefined)},
 async getAccount(accessToken){const response=await fetch("https://gmail.googleapis.com/gmail/v1/users/me/profile",{headers:{authorization:`Bearer ${accessToken}`},signal:AbortSignal.timeout(10_000)});if(!response.ok)throw new Error("GMAIL_PROFILE_FAILED");const data=await response.json();return{id:data.emailAddress,email:data.emailAddress}}
};
