import type { EmailProviderClient, ProviderTokens } from "./types";
type MicrosoftMessageSummary={id:string;conversationId?:string};
const tenant=()=>process.env.MICROSOFT_EMAIL_TENANT_ID??"common";
const credentials=()=>{const clientId=process.env.MICROSOFT_EMAIL_CLIENT_ID,clientSecret=process.env.MICROSOFT_EMAIL_CLIENT_SECRET;if(!clientId||!clientSecret)throw new Error("MICROSOFT_OAUTH_NOT_CONFIGURED");return{clientId,clientSecret}};
const tokenUrl=()=>`https://login.microsoftonline.com/${tenant()}/oauth2/v2.0/token`;
async function tokenRequest(body:URLSearchParams):Promise<ProviderTokens>{const response=await fetch(tokenUrl(),{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body,signal:AbortSignal.timeout(15_000)});if(!response.ok)throw new Error(`MICROSOFT_TOKEN_${response.status}`);const value=await response.json();return{accessToken:value.access_token,refreshToken:value.refresh_token,expiresAt:new Date(Date.now()+value.expires_in*1000).toISOString(),scopes:(value.scope??"Mail.Read User.Read offline_access").split(" ")}}
export const microsoftProvider:EmailProviderClient={
 async connect(code,redirectUri){const c=credentials();return tokenRequest(new URLSearchParams({client_id:c.clientId,client_secret:c.clientSecret,code,redirect_uri:redirectUri,grant_type:"authorization_code",scope:"openid email offline_access User.Read Mail.Read"}))},
 async refreshToken(refreshToken){const c=credentials();return tokenRequest(new URLSearchParams({client_id:c.clientId,client_secret:c.clientSecret,refresh_token:refreshToken,grant_type:"refresh_token",scope:"openid email offline_access User.Read Mail.Read"}))},
 async listMessages(accessToken,cursor,lastSyncAt){let url:string;if(cursor?.startsWith("https://"))url=cursor;else{const base=new URL("https://graph.microsoft.com/v1.0/me/mailFolders/inbox/messages/delta");base.searchParams.set("$select","id,conversationId");base.searchParams.set("$top","100");if(lastSyncAt)base.searchParams.set("$filter",`receivedDateTime ge ${lastSyncAt}`);url=base.toString()}const response=await fetch(url,{headers:{authorization:`Bearer ${accessToken}`},signal:AbortSignal.timeout(20_000)});if(!response.ok)throw new Error(`MICROSOFT_LIST_${response.status}`);const data=await response.json()as{value?:MicrosoftMessageSummary[];"@odata.nextLink"?:string;"@odata.deltaLink"?:string};return{messages:(data.value??[]).map(item=>({id:item.id,threadId:item.conversationId})),nextCursor:data["@odata.nextLink"]??data["@odata.deltaLink"]}},
 async getMessage(accessToken,messageId){const url=new URL(`https://graph.microsoft.com/v1.0/me/messages/${encodeURIComponent(messageId)}`);url.searchParams.set("$select","id,conversationId,subject,from,receivedDateTime,body");const response=await fetch(url,{headers:{authorization:`Bearer ${accessToken}`,"Prefer":'outlook.body-content-type="text"'},signal:AbortSignal.timeout(20_000)});if(!response.ok)throw new Error(`MICROSOFT_MESSAGE_${response.status}`);const data=await response.json();return{id:data.id,threadId:data.conversationId,senderEmail:data.from?.emailAddress?.address??null,subject:data.subject??"",receivedAt:data.receivedDateTime,text:String(data.body?.content??"").slice(0,20_000)}},
 async disconnect(){},
 async getAccount(accessToken){const response=await fetch("https://graph.microsoft.com/v1.0/me?$select=id,mail,userPrincipalName",{headers:{authorization:`Bearer ${accessToken}`},signal:AbortSignal.timeout(10_000)});if(!response.ok)throw new Error("MICROSOFT_PROFILE_FAILED");const data=await response.json();return{id:data.id,email:data.mail??data.userPrincipalName}}
};
