"use client";

import { useActionState } from "react";
import { Plus, RefreshCw, Trash2 } from "lucide-react";
import { addSkill, recalculateMyMatches } from "@/lib/actions/skills";
import { skillDisplayName } from "@/lib/matching/normalize-skill";

export function SkillsSection({ skills, removeAction }: { skills: { id: string; skill: string; source: string }[]; removeAction: (formData: FormData) => void }) {
  const [addState, addAction, adding] = useActionState(addSkill, {});
  const [matchState, matchAction, calculating] = useActionState(recalculateMyMatches, {});
  return <section className="card p-6 sm:p-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><h2 className="text-lg font-semibold">Skills</h2><p className="mt-1 text-sm text-zinc-500">Add skills that should influence your job matches.</p></div><form action={matchAction}><button disabled={calculating} className="button-secondary !px-4 !py-2"><RefreshCw className={`size-4 ${calculating ? "animate-spin" : ""}`} />{calculating ? "Calculating…" : "Recalculate My Matches"}</button></form></div><form action={addAction} className="mt-6 flex flex-col gap-3 sm:flex-row"><label className="sr-only" htmlFor="new-skill">New skill</label><input id="new-skill" name="skill" className="min-w-0 flex-1 rounded-xl border bg-zinc-50 px-4 py-3 text-sm outline-none focus:border-accent-500 focus:ring-2 focus:ring-accent-100" placeholder="Try JavaScript, React.js, PostgreSQL, or Figma" required maxLength={100} /><button disabled={adding} className="button-primary"><Plus className="size-4" />{adding ? "Adding…" : "Add skill"}</button></form>{addState.error && <p className="mt-3 text-sm text-rose-600">{addState.error}</p>}{addState.success && <p className="mt-3 text-sm text-emerald-600">{addState.success}</p>}<div className="mt-6 flex flex-wrap gap-2">{skills.length ? skills.map(item => <span key={item.id} className="inline-flex items-center gap-2 rounded-xl bg-accent-50 px-3 py-2 text-sm font-medium text-accent-700">{skillDisplayName(item.skill)}<span className="text-[10px] uppercase text-accent-400">{item.source}</span><form action={removeAction}><input type="hidden" name="id" value={item.id} /><button className="text-accent-400 hover:text-rose-600" aria-label={`Remove ${item.skill}`}><Trash2 className="size-3.5" /></button></form></span>) : <p className="text-sm text-zinc-500">No skills added yet. Start with the tools you use confidently.</p>}</div>{matchState.error && <p className="mt-5 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{matchState.error}</p>}{matchState.summary && <p className="mt-5 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">Evaluated {matchState.summary.jobsEvaluated} jobs · {matchState.summary.matchesCreated} created · {matchState.summary.matchesUpdated} updated · {matchState.summary.failures} failed.</p>}</section>;
}
