import { DashboardHeader } from "@/components/dashboard-header";
import { createClient } from "@/lib/supabase/server";
import { deleteEmailMetadata,disconnectEmailConnection,pauseEmailConnection,requestEmailSync,resumeEmailConnection,setEmailAiConsent } from "@/lib/actions/email";
export default async function EmailIntegrationsPage({searchParams}:{searchParams:Promise<{connected?:string;error?:string}>}){
 const params=await searchParams,db=await createClient();
 const[{data:connections},{data:consent}]=await Promise.all([db.from("email_connections").select("id,provider,email_address,status,last_sync_at,last_successful_sync_at,last_error_code,scopes,connected_at").order("connected_at",{ascending:false}),db.from("user_consents").select("granted").eq("consent_type","AI_EMAIL_CLASSIFICATION").eq("version","2026-08-08").maybeSingle()]);
 return <><DashboardHeader title="Recruiter email tracking" subtitle="Connect with OAuth. JobPilot never asks for your mailbox password or sends email."/><main className="mx-auto max-w-4xl space-y-6 p-5 sm:p-8">
 {params.connected&&<p className="rounded-xl bg-emerald-50 p-4 text-sm text-emerald-800">Mailbox connected. Request a sync when you are ready.</p>}
 {params.error&&<p className="rounded-xl bg-rose-50 p-4 text-sm text-rose-700">The mailbox connection could not be completed. Check provider configuration and try again.</p>}
 <section className="card p-6"><h2 className="font-semibold">Connect a mailbox</h2><p className="mt-2 text-sm text-zinc-500">Read-only access identifies application updates. Full message bodies are not stored.</p><div className="mt-4 flex flex-wrap gap-3"><a className="button-primary" href="/api/email/oauth/gmail/start">Connect Gmail</a><a className="button-secondary" href="/api/email/oauth/microsoft/start">Connect Microsoft</a></div></section>
 <section className="space-y-3"><h2 className="font-semibold">Connections</h2>{connections?.length?connections.map(connection=><article className="card p-5" key={connection.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold">{connection.email_address}</p><p className="text-xs text-zinc-500">{connection.provider} · {connection.status}</p><p className="mt-2 text-xs text-zinc-500">Last successful sync: {connection.last_successful_sync_at?new Date(connection.last_successful_sync_at).toLocaleString():"Never"}</p>{connection.last_error_code&&<p className="mt-1 text-xs text-rose-600">Connection needs attention: {connection.last_error_code}</p>}</div><div className="flex flex-wrap gap-2">{connection.status==="ACTIVE"?<><form action={requestEmailSync}><input type="hidden" name="connectionId" value={connection.id}/><button className="button-primary !py-2">Sync now</button></form><form action={pauseEmailConnection}><input type="hidden" name="connectionId" value={connection.id}/><button className="button-secondary !py-2">Pause</button></form></>:connection.status==="EXPIRED"?<form action={resumeEmailConnection}><input type="hidden" name="connectionId" value={connection.id}/><button className="button-secondary !py-2">Resume</button></form>:null}<form action={disconnectEmailConnection}><input type="hidden" name="connectionId" value={connection.id}/><button className="button-secondary !py-2">Disconnect</button></form></div></div></article>):<div className="card p-8 text-center text-sm text-zinc-500">No mailbox connected.</div>}</section>
 <section className="card p-6"><h2 className="font-semibold">Ambiguous-message AI review</h2><p className="mt-2 text-sm text-zinc-500">Optional: allow a redacted excerpt from job-related messages that rules cannot classify to be analyzed by Gemini. Results always require your review.</p><form action={setEmailAiConsent} className="mt-4 flex items-center gap-3"><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="granted" defaultChecked={Boolean(consent?.granted)}/>Allow AI classification</label><button className="button-secondary !py-2">Save</button></form></section>
 <section className="card border-rose-100 p-6"><h2 className="font-semibold">Delete imported email metadata</h2><p className="mt-2 text-sm text-zinc-500">This removes sender, subject, classifications, and matches. It does not delete existing application history derived from confirmed updates.</p><form action={deleteEmailMetadata} className="mt-4 flex gap-2"><input className="input flex-1" name="confirmation" placeholder="Type DELETE EMAIL METADATA" required/><button className="button-secondary text-rose-700">Delete metadata</button></form></section>
 </main></>
}
