import Link from "next/link";
import { DashboardHeader } from "@/components/dashboard-header";
import { ApplicationStatusBadge } from "@/components/applications/application-status-badge";
import { createClient } from "@/lib/supabase/server";
import type { ApplicationStatus } from "@/lib/applications/types";

interface Row{id:string;status:ApplicationStatus;match_score:number|null;last_activity_at:string;selected_resume_draft_id:string|null;selected_cover_letter_draft_id:string|null;jobs:{id:string;title:string;location:string|null;status:string;companies:{name:string}}}
const groups=[{title:"Needs preparation",statuses:["SAVED","PREPARING"]},{title:"Needs review",statuses:["NEEDS_REVIEW"]},{title:"Ready to apply",statuses:["READY_TO_APPLY"]},{title:"In progress",statuses:["APPLYING","NEEDS_USER_ACTION","FAILED"]},{title:"Submitted",statuses:["SUBMITTED","INTERVIEW"]},{title:"Closed",statuses:["REJECTED","OFFER","WITHDRAWN","ARCHIVED"]}] as const;
function next(status:ApplicationStatus){if(status==="SAVED"||status==="PREPARING")return "Prepare documents";if(status==="NEEDS_REVIEW")return "Review and approve documents";if(status==="READY_TO_APPLY")return "Open employer application";if(status==="APPLYING")return "Confirm whether you submitted";if(status==="NEEDS_USER_ACTION")return "Resolve required action";return "View application";}
export default async function ApplicationsPage(){const db=await createClient();const {data}=await db.from("applications").select("id,status,match_score,last_activity_at,selected_resume_draft_id,selected_cover_letter_draft_id,jobs!inner(id,title,location,status,companies!inner(name))").order("last_activity_at",{ascending:false});const rows=(data??[]) as unknown as Row[];return <><DashboardHeader title="Applications" subtitle="Every application, document, and next step."/><main className="space-y-8 p-5 sm:p-8">{groups.map(group=>{const items=rows.filter(r=>(group.statuses as readonly string[]).includes(r.status));return <section key={group.title}><div className="mb-3 flex items-center justify-between"><h2 className="font-semibold">{group.title}</h2><span className="text-xs font-semibold text-zinc-400">{items.length}</span></div>{items.length?<div className="grid gap-4 lg:grid-cols-2">{items.map(app=><Link href={`/applications/${app.id}`} key={app.id} className="card p-5 transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-medium text-zinc-500">{app.jobs.companies.name}</p><h3 className="mt-1 font-semibold">{app.jobs.title}</h3><p className="mt-1 text-xs text-zinc-400">{app.jobs.location??"Location not listed"}</p></div><ApplicationStatusBadge status={app.status}/></div>{app.jobs.status!=="active"&&!(["SUBMITTED","INTERVIEW","REJECTED","OFFER"] as string[]).includes(app.status)&&<p className="mt-3 rounded-lg bg-amber-50 p-2 text-xs text-amber-800">This job is no longer listed by the employer.</p>}<div className="mt-4 grid grid-cols-3 gap-2 text-xs"><span>{app.match_score??"--"}% match</span><span>Resume: {app.selected_resume_draft_id?"approved":"pending"}</span><span>Cover: {app.selected_cover_letter_draft_id?"approved":"pending"}</span></div><div className="mt-4 border-t pt-3 text-xs font-semibold text-accent-700">{next(app.status)}</div></Link>)}</div>:<div className="rounded-2xl border border-dashed p-6 text-sm text-zinc-400">No applications here.</div>}</section>})}</main></>}
