"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { decryptToken } from "@/lib/email/token-crypto";
import { emailProvider } from "@/lib/email/providers";
import { transitionApplication } from "@/lib/applications/status-machine";
const uuid=z.string().uuid();
async function currentUser(){const db=await createClient(),{data:{user}}=await db.auth.getUser();if(!user)throw new Error("UNAUTHORIZED");return user}
export async function requestEmailSync(formData:FormData){const connectionId=uuid.parse(formData.get("connectionId")),user=await currentUser(),db=createAdminClient(),{data:connection}=await db.from("email_connections").select("id").eq("id",connectionId).eq("user_id",user.id).eq("status","ACTIVE").maybeSingle();if(!connection)throw new Error("CONNECTION_NOT_ACTIVE");const{data:pending}=await db.from("email_sync_requests").select("id").eq("connection_id",connectionId).in("status",["PENDING","QUEUED"]).maybeSingle();if(!pending)await db.from("email_sync_requests").insert({user_id:user.id,connection_id:connectionId,status:"PENDING"});revalidatePath("/settings/integrations/email")}
export async function pauseEmailConnection(formData:FormData){const id=uuid.parse(formData.get("connectionId")),user=await currentUser();await createAdminClient().from("email_connections").update({status:"EXPIRED"}).eq("id",id).eq("user_id",user.id);revalidatePath("/settings/integrations/email")}
export async function resumeEmailConnection(formData:FormData){const id=uuid.parse(formData.get("connectionId")),user=await currentUser();await createAdminClient().from("email_connections").update({status:"ACTIVE"}).eq("id",id).eq("user_id",user.id);revalidatePath("/settings/integrations/email")}
export async function disconnectEmailConnection(formData:FormData){const id=uuid.parse(formData.get("connectionId")),user=await currentUser(),db=createAdminClient(),{data}=await db.from("email_connections").select("provider,encrypted_access_token,encrypted_refresh_token").eq("id",id).eq("user_id",user.id).maybeSingle();if(!data)return;try{await emailProvider(data.provider).disconnect(data.encrypted_access_token?decryptToken(data.encrypted_access_token):undefined,data.encrypted_refresh_token?decryptToken(data.encrypted_refresh_token):undefined)}catch{}await db.from("email_connections").update({status:"DISCONNECTED",encrypted_access_token:null,encrypted_refresh_token:null,sync_cursor:null}).eq("id",id).eq("user_id",user.id);revalidatePath("/settings/integrations/email")}
export async function deleteEmailMetadata(formData:FormData){const user=await currentUser();if(formData.get("confirmation")!=="DELETE EMAIL METADATA")throw new Error("CONFIRMATION_REQUIRED");await createAdminClient().from("application_email_events").delete().eq("user_id",user.id);revalidatePath("/inbox")}
export async function setEmailAiConsent(formData:FormData){const user=await currentUser();await createAdminClient().from("user_consents").upsert({user_id:user.id,consent_type:"AI_EMAIL_CLASSIFICATION",version:"2026-08-08",granted:formData.get("granted")==="on"},{onConflict:"user_id,consent_type,version"});revalidatePath("/settings/integrations/email")}
export async function reviewEmailEvent(formData:FormData){const eventId=uuid.parse(formData.get("eventId")),decision=z.enum(["confirm","dismiss"]).parse(formData.get("decision")),user=await currentUser(),db=createAdminClient(),{data:event}=await db.from("application_email_events").select("id,application_id,proposed_status,review_status").eq("id",eventId).eq("user_id",user.id).maybeSingle();if(!event||event.review_status!=="PENDING")return;if(decision==="dismiss"){await db.from("application_email_events").update({review_status:"DISMISSED"}).eq("id",eventId).eq("user_id",user.id)}else{if(event.application_id&&event.proposed_status)await transitionApplication(event.application_id,user.id,event.proposed_status,{manual:true,eventType:"EMAIL_STATUS_CONFIRMED",data:{emailEventId:event.id}});await db.from("application_email_events").update({review_status:"CONFIRMED"}).eq("id",eventId).eq("user_id",user.id)}revalidatePath("/inbox");revalidatePath("/applications");redirect("/inbox")}
