import{z}from"zod";import type{AtsType}from"./platform/types";
export const detectionSchema=z.object({atsType:z.enum(["GREENHOUSE","LEVER","ASHBY","SMARTRECRUITERS","WORKABLE","WORKDAY","GENERIC","UNKNOWN"]),confidence:z.number().min(0).max(1),identifier:z.string().nullable(),reason:z.string()});
export type CareerSourceDetection=z.infer<typeof detectionSchema>;
const rules:Array<{atsType:AtsType;hosts:RegExp;identifier:(u:URL)=>string|null;reason:string}>=[
 {atsType:"GREENHOUSE",hosts:/(boards-api|boards|job-boards)\.greenhouse\.io$/,identifier:u=>u.hostname.startsWith("boards-api")?u.pathname.split("/").filter(Boolean)[2]??null:u.pathname.split("/").filter(Boolean)[0]??null,reason:"Known Greenhouse public board hostname"},
 {atsType:"LEVER",hosts:/(jobs|api)\.lever\.co$/,identifier:u=>u.pathname.split("/").filter(Boolean).at(u.hostname.startsWith("api")?2:0)??null,reason:"Known Lever public postings hostname"},
 {atsType:"ASHBY",hosts:/(jobs|api)\.ashbyhq\.com$/,identifier:u=>u.pathname.split("/").filter(Boolean).at(u.hostname.startsWith("api")?2:0)??null,reason:"Known Ashby public job-board hostname"},
 {atsType:"SMARTRECRUITERS",hosts:/(careers|jobs|api)\.smartrecruiters\.com$/,identifier:u=>u.pathname.split("/").filter(Boolean).at(u.hostname.startsWith("api")?2:0)??null,reason:"Known SmartRecruiters career hostname"},
 {atsType:"WORKABLE",hosts:/(apply|jobs|www)\.workable\.com$/,identifier:u=>u.pathname.split("/").filter(Boolean)[0]??null,reason:"Known Workable careers hostname"},
 {atsType:"WORKDAY",hosts:/((myworkdayjobs|workday)\.com|wd\d+\.myworkdaysite\.com)$/,identifier:()=>null,reason:"Workday detected; configuration requires manual review"},
];
export function detectCareerSource(input:string,markup=""):CareerSourceDetection{let url:URL;try{url=new URL(input)}catch{return{atsType:"UNKNOWN",confidence:0,identifier:null,reason:"Invalid URL"}}for(const rule of rules)if(rule.hosts.test(url.hostname.toLowerCase())){const identifier=rule.identifier(url);return{atsType:rule.atsType,confidence:rule.atsType==="WORKDAY"?.75:identifier?.99:.7,identifier,reason:rule.reason}}const signatures:Array<[RegExp,AtsType,string]>=commonSignatures();for(const[pattern,ats,reason]of signatures)if(pattern.test(markup))return{atsType:ats,confidence:.75,identifier:null,reason};return{atsType:"UNKNOWN",confidence:.2,identifier:null,reason:"No trusted ATS signature; manual review required"};}
function commonSignatures():Array<[RegExp,AtsType,string]>{return[[/greenhouse\.io/i,"GREENHOUSE","Greenhouse link found in supplied markup"],[/jobs\.lever\.co/i,"LEVER","Lever link found in supplied markup"],[/jobs\.ashbyhq\.com/i,"ASHBY","Ashby link found in supplied markup"],[/smartrecruiters\.com/i,"SMARTRECRUITERS","SmartRecruiters link found in supplied markup"],[/apply\.workable\.com/i,"WORKABLE","Workable link found in supplied markup"]]}
