-- JobPilot Phase 8: explicit-approval submission sessions, snapshots, tokens, and receipts.
create table if not exists public.application_sessions(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,application_id uuid not null references public.applications(id) on delete cascade,ats_type text not null check(ats_type in('GREENHOUSE','LEVER','GENERIC')),status text not null default 'CREATED' check(status in('CREATED','FORM_DETECTED','FILLING','WAITING_FOR_USER','READY_FOR_REVIEW','APPROVED_TO_SUBMIT','SUBMITTING','SUBMITTED','FAILED','EXPIRED')),started_at timestamptz not null default timezone('utc',now()),expires_at timestamptz not null,completed_at timestamptz,failure_code text,created_at timestamptz not null default timezone('utc',now()),updated_at timestamptz not null default timezone('utc',now()));
create unique index if not exists one_active_submission_session on public.application_sessions(application_id) where status in('CREATED','FORM_DETECTED','FILLING','WAITING_FOR_USER','READY_FOR_REVIEW','APPROVED_TO_SUBMIT','SUBMITTING');create index if not exists application_sessions_user_idx on public.application_sessions(user_id,created_at desc);
create table if not exists public.application_form_snapshots(id uuid primary key default gen_random_uuid(),application_id uuid not null references public.applications(id) on delete cascade,session_id uuid not null references public.application_sessions(id) on delete cascade,form_hash text not null check(form_hash~'^[a-f0-9]{64}$'),field_summary jsonb not null,warnings jsonb not null default '[]',missing_required_fields jsonb not null default '[]',document_versions jsonb not null,created_at timestamptz not null default timezone('utc',now()),unique(session_id,form_hash));
create table if not exists public.submission_approval_tokens(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,application_id uuid not null references public.applications(id) on delete cascade,session_id uuid not null references public.application_sessions(id) on delete cascade,form_snapshot_hash text not null,token_hash text not null unique check(token_hash~'^[a-f0-9]{64}$'),expires_at timestamptz not null,used_at timestamptz,created_at timestamptz not null default timezone('utc',now()),unique(application_id,form_snapshot_hash));
create table if not exists public.application_receipts(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,application_id uuid not null references public.applications(id) on delete cascade,session_id uuid not null references public.application_sessions(id) on delete restrict,ats_type text not null,submitted_at timestamptz not null,confirmation_text text,confirmation_reference text,confirmation_url text,screenshot_path text,field_summary jsonb not null default '[]',created_at timestamptz not null default timezone('utc',now()),unique(application_id));
create index if not exists form_snapshots_application_idx on public.application_form_snapshots(application_id,created_at desc);create index if not exists receipts_user_idx on public.application_receipts(user_id,submitted_at desc);
drop trigger if exists application_sessions_updated_at on public.application_sessions;create trigger application_sessions_updated_at before update on public.application_sessions for each row execute function public.set_updated_at();
alter table public.application_sessions enable row level security;alter table public.application_form_snapshots enable row level security;alter table public.submission_approval_tokens enable row level security;alter table public.application_receipts enable row level security;
drop policy if exists "Users read own submission sessions" on public.application_sessions;drop policy if exists "Users read own form snapshots" on public.application_form_snapshots;drop policy if exists "Users read own receipts" on public.application_receipts;
create policy "Users read own submission sessions" on public.application_sessions for select to authenticated using((select auth.uid())=user_id);create policy "Users read own form snapshots" on public.application_form_snapshots for select to authenticated using(exists(select 1 from public.applications a where a.id=application_id and a.user_id=(select auth.uid())));create policy "Users read own receipts" on public.application_receipts for select to authenticated using((select auth.uid())=user_id);
-- Approval tokens have no client policies. All writes are trusted server operations.
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)values('automation-screenshots','automation-screenshots',false,5242880,array['image/png','image/jpeg'])on conflict(id)do update set public=false;
drop policy if exists "Users read own automation screenshots" on storage.objects;create policy "Users read own automation screenshots" on storage.objects for select to authenticated using(bucket_id='automation-screenshots' and (storage.foldername(name))[1]=(select auth.uid())::text);
notify pgrst,'reload schema';
