-- JobPilot Phase 10: billing, immutable usage, consent, flags, audits, worker health, and notification preferences.
create table if not exists public.subscription_plans(id uuid primary key default gen_random_uuid(),code text not null unique check(code in('FREE','STARTER','PRO')),name text not null,stripe_price_id text unique,limits jsonb not null default '{}'::jsonb,active boolean not null default true,created_at timestamptz not null default timezone('utc',now()),updated_at timestamptz not null default timezone('utc',now()));
insert into public.subscription_plans(code,name,limits)values
('FREE','Free','{"AI_RESUME_ANALYSIS":2,"DOCUMENT_GENERATION":3,"MATCH_RECALCULATION":5,"ASSISTED_APPLICATION_SESSION":3,"AUTOMATED_SUBMISSION_ATTEMPT":0}'::jsonb),
('STARTER','Starter','{"AI_RESUME_ANALYSIS":20,"DOCUMENT_GENERATION":40,"MATCH_RECALCULATION":100,"ASSISTED_APPLICATION_SESSION":30,"AUTOMATED_SUBMISSION_ATTEMPT":10}'::jsonb),
('PRO','Pro','{"AI_RESUME_ANALYSIS":100,"DOCUMENT_GENERATION":200,"MATCH_RECALCULATION":500,"ASSISTED_APPLICATION_SESSION":150,"AUTOMATED_SUBMISSION_ATTEMPT":75}'::jsonb)
on conflict(code)do nothing;
create table if not exists public.subscriptions(id uuid primary key default gen_random_uuid(),user_id uuid not null unique references auth.users(id) on delete cascade,plan_id uuid not null references public.subscription_plans(id),stripe_customer_id text unique,stripe_subscription_id text unique,status text not null default 'free',current_period_start timestamptz,current_period_end timestamptz,cancel_at_period_end boolean not null default false,created_at timestamptz not null default timezone('utc',now()),updated_at timestamptz not null default timezone('utc',now()));
create table if not exists public.billing_events(id uuid primary key default gen_random_uuid(),stripe_event_id text not null unique,event_type text not null,user_id uuid references auth.users(id) on delete set null,payload_summary jsonb not null default '{}'::jsonb,processed_at timestamptz not null default timezone('utc',now()),created_at timestamptz not null default timezone('utc',now()));
create table if not exists public.usage_events(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,operation text not null,quantity integer not null check(quantity>0),application_id uuid references public.applications(id) on delete set null,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default timezone('utc',now()));
create table if not exists public.usage_counters(user_id uuid not null references auth.users(id) on delete cascade,operation text not null,period_start date not null,quantity integer not null default 0 check(quantity>=0),updated_at timestamptz not null default timezone('utc',now()),primary key(user_id,operation,period_start));
create table if not exists public.user_consents(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,consent_type text not null,version text not null,granted boolean not null,created_at timestamptz not null default timezone('utc',now()),unique(user_id,consent_type,version));
create table if not exists public.feature_flags(key text primary key,enabled boolean not null default false,description text,updated_by uuid references auth.users(id) on delete set null,updated_at timestamptz not null default timezone('utc',now()));
insert into public.feature_flags(key,enabled,description)values('AI_DOCUMENTS',true,'Gemini document preparation'),('ASSISTED_APPLICATIONS',true,'Extension assisted filling'),('AUTOMATED_SUBMISSION',false,'Controlled employer final submission'),('NEW_ATS_CONNECTORS',false,'Non-Greenhouse ingestion connectors')on conflict(key)do nothing;
create table if not exists public.admin_audit_logs(id uuid primary key default gen_random_uuid(),actor_user_id uuid references auth.users(id) on delete set null,action text not null,target_type text,target_id text,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default timezone('utc',now()));
create table if not exists public.worker_instances(id uuid primary key,hostname text not null,version text not null,started_at timestamptz not null,last_heartbeat_at timestamptz not null,metadata jsonb not null default '{}'::jsonb);
create table if not exists public.notification_preferences(user_id uuid primary key references auth.users(id) on delete cascade,application_updates boolean not null default true,document_updates boolean not null default true,billing_updates boolean not null default true,product_updates boolean not null default false,email_enabled boolean not null default false,updated_at timestamptz not null default timezone('utc',now()));
create index if not exists usage_events_user_period_idx on public.usage_events(user_id,operation,created_at desc);create index if not exists billing_events_type_idx on public.billing_events(event_type,created_at desc);create index if not exists admin_audit_logs_action_idx on public.admin_audit_logs(action,created_at desc);create index if not exists worker_instances_heartbeat_idx on public.worker_instances(last_heartbeat_at desc);create index if not exists application_events_user_created_idx on public.application_events(user_id,created_at desc);create index if not exists job_matches_user_score_idx on public.job_matches(user_id,overall_score desc);
drop trigger if exists subscription_plans_updated_at on public.subscription_plans;create trigger subscription_plans_updated_at before update on public.subscription_plans for each row execute function public.set_updated_at();drop trigger if exists subscriptions_updated_at on public.subscriptions;create trigger subscriptions_updated_at before update on public.subscriptions for each row execute function public.set_updated_at();
alter table public.subscription_plans enable row level security;alter table public.subscriptions enable row level security;alter table public.billing_events enable row level security;alter table public.usage_events enable row level security;alter table public.usage_counters enable row level security;alter table public.user_consents enable row level security;alter table public.feature_flags enable row level security;alter table public.admin_audit_logs enable row level security;alter table public.worker_instances enable row level security;alter table public.notification_preferences enable row level security;
create policy "Users read active plans" on public.subscription_plans for select to authenticated using(active=true);create policy "Users read own subscription" on public.subscriptions for select to authenticated using((select auth.uid())=user_id);create policy "Users read own usage" on public.usage_events for select to authenticated using((select auth.uid())=user_id);create policy "Users read own counters" on public.usage_counters for select to authenticated using((select auth.uid())=user_id);create policy "Users manage own consents" on public.user_consents for all to authenticated using((select auth.uid())=user_id)with check((select auth.uid())=user_id);create policy "Users manage notification preferences" on public.notification_preferences for all to authenticated using((select auth.uid())=user_id)with check((select auth.uid())=user_id);
-- Billing events, counters, flags, audits, and worker heartbeats have no client write policies.
notify pgrst,'reload schema';
